/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as zkVote from "./ZKVote";
export type { zkVote };
import type * as interfaces from "./interfaces";
export type { interfaces };
export type { ZK_RFP } from "./ZK_RFP";
