/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as merkleTreeWithHistorySol from "./MerkleTreeWithHistory.sol";
export type { merkleTreeWithHistorySol };
import type * as zkTreeSol from "./ZKTree.sol";
export type { zkTreeSol };
