/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IAnchor,
  IAnchorInterface,
} from "../../../contracts/interfaces/IAnchor";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_target",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_value",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "_data",
        type: "bytes",
      },
    ],
    name: "execute",
    outputs: [
      {
        internalType: "bytes",
        name: "",
        type: "bytes",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IAnchor__factory {
  static readonly abi = _abi;
  static createInterface(): IAnchorInterface {
    return new utils.Interface(_abi) as IAnchorInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IAnchor {
    return new Contract(address, _abi, signerOrProvider) as IAnchor;
  }
}
